apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev-namespace
  labels:
    app: app
   
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
kind: Service
metadata:
  name: app-service
  namespace: dev-namespace
spec:
  selector:
      app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: clusterIP

 