name: multi build
on: [push,workflow_dispatch]
jobs:
  runs-on: self-hosted 
  steps: 
    -name: checkout 
    -uses: actions/checkout@v2
    -name: login to azure
    -uses : azure/login@v1
    -with :
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      